{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6991862e-37f9-41e0-a9ff-4a5628997d4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# \"\"\"\n",
    "# ╔══════════════════════════════════════════════════════════════════════╗\n",
    "# ║   EduXAI — Student Performance Analytics using Explainable AI       ║\n",
    "# ║   Dataset : UCI Student Performance (1044 students)                 ║\n",
    "# ║   Model   : Normalized Linear Model (G1=G2 balanced, SchoolSup +)  ║\n",
    "# ║   Run     : py -m streamlit run app.py                              ║\n",
    "# ╚══════════════════════════════════════════════════════════════════════╝\n",
    "# \"\"\"\n",
    "\n",
    "# import streamlit as st\n",
    "# import pandas as pd\n",
    "# import numpy as np\n",
    "# import plotly.graph_objects as go\n",
    "# import plotly.express as px\n",
    "# from plotly.subplots import make_subplots\n",
    "# import pickle\n",
    "# import os\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # PAGE CONFIG\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# st.set_page_config(\n",
    "#     page_title=\"EduXAI · Student Performance Analytics\",\n",
    "#     page_icon=\"🎓\",\n",
    "#     layout=\"wide\",\n",
    "#     initial_sidebar_state=\"expanded\"\n",
    "# )\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # CUSTOM CSS — Dark futuristic theme\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# st.markdown(\"\"\"\n",
    "# <style>\n",
    "# @import url('https://fonts.googleapis.com/css2?family=Sora:wght@300;400;600;700;800&family=DM+Mono:wght@400;500;600&display=swap');\n",
    "\n",
    "# html, body, [class*=\"css\"] {\n",
    "#     font-family: 'Sora', sans-serif !important;\n",
    "#     background-color: #080d18 !important;\n",
    "#     color: #e2e8f0 !important;\n",
    "# }\n",
    "# .main { background-color: #080d18 !important; }\n",
    "# .block-container { padding: 1.5rem 2rem !important; max-width: 1400px !important; }\n",
    "\n",
    "# /* Sidebar */\n",
    "# [data-testid=\"stSidebar\"] {\n",
    "#     background: #0d1526 !important;\n",
    "#     border-right: 1px solid rgba(255,255,255,0.07) !important;\n",
    "# }\n",
    "# [data-testid=\"stSidebar\"] .block-container { padding: 1rem !important; }\n",
    "\n",
    "# /* Cards */\n",
    "# .xai-card {\n",
    "#     background: rgba(255,255,255,0.035);\n",
    "#     border: 1px solid rgba(255,255,255,0.08);\n",
    "#     border-radius: 16px;\n",
    "#     padding: 20px 22px;\n",
    "#     margin-bottom: 16px;\n",
    "# }\n",
    "# .xai-card:hover { border-color: rgba(110,231,247,0.2); transition: border-color 0.3s; }\n",
    "\n",
    "# /* Metric cards */\n",
    "# .metric-card {\n",
    "#     background: rgba(255,255,255,0.03);\n",
    "#     border: 1px solid rgba(255,255,255,0.07);\n",
    "#     border-radius: 14px;\n",
    "#     padding: 18px;\n",
    "#     text-align: center;\n",
    "# }\n",
    "# .metric-val  { font-family: 'DM Mono', monospace; font-size: 2rem; font-weight: 800; line-height: 1; }\n",
    "# .metric-label { font-size: 0.7rem; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }\n",
    "# .metric-sub   { font-size: 0.7rem; color: #475569; margin-top: 2px; }\n",
    "\n",
    "# /* Section headers */\n",
    "# .section-header {\n",
    "#     font-size: 0.75rem;\n",
    "#     font-weight: 800;\n",
    "#     color: #94a3b8;\n",
    "#     text-transform: uppercase;\n",
    "#     letter-spacing: 1.5px;\n",
    "#     margin-bottom: 14px;\n",
    "#     display: flex;\n",
    "#     align-items: center;\n",
    "#     gap: 8px;\n",
    "# }\n",
    "\n",
    "# /* Result banner */\n",
    "# .result-pass {\n",
    "#     background: rgba(52,211,153,0.08);\n",
    "#     border: 1px solid rgba(52,211,153,0.3);\n",
    "#     border-radius: 12px;\n",
    "#     padding: 16px 20px;\n",
    "#     text-align: center;\n",
    "# }\n",
    "# .result-fail {\n",
    "#     background: rgba(251,113,133,0.08);\n",
    "#     border: 1px solid rgba(251,113,133,0.3);\n",
    "#     border-radius: 12px;\n",
    "#     padding: 16px 20px;\n",
    "#     text-align: center;\n",
    "# }\n",
    "\n",
    "# /* Badge */\n",
    "# .badge {\n",
    "#     display: inline-block;\n",
    "#     font-size: 0.65rem;\n",
    "#     font-weight: 700;\n",
    "#     padding: 3px 10px;\n",
    "#     border-radius: 20px;\n",
    "#     letter-spacing: 0.5px;\n",
    "#     text-transform: uppercase;\n",
    "# }\n",
    "# .badge-cyan   { background: rgba(110,231,247,0.1);  border: 1px solid rgba(110,231,247,0.3);  color: #6ee7f7; }\n",
    "# .badge-green  { background: rgba(52,211,153,0.1);   border: 1px solid rgba(52,211,153,0.3);   color: #34d399; }\n",
    "# .badge-rose   { background: rgba(251,113,133,0.1);  border: 1px solid rgba(251,113,133,0.3);  color: #fb7185; }\n",
    "# .badge-violet { background: rgba(167,139,250,0.1);  border: 1px solid rgba(167,139,250,0.3);  color: #a78bfa; }\n",
    "# .badge-amber  { background: rgba(251,191,36,0.1);   border: 1px solid rgba(251,191,36,0.3);   color: #fbbf24; }\n",
    "\n",
    "# /* Risk row */\n",
    "# .risk-row-ok   { background: rgba(52,211,153,0.04);  border: 1px solid rgba(52,211,153,0.15);  border-radius: 10px; padding: 10px 14px; margin-bottom: 8px; }\n",
    "# .risk-row-warn { background: rgba(251,113,133,0.04); border: 1px solid rgba(251,113,133,0.15); border-radius: 10px; padding: 10px 14px; margin-bottom: 8px; }\n",
    "\n",
    "# /* Streamlit widget overrides */\n",
    "# div[data-testid=\"stSlider\"] > div > div > div > div { background: #6ee7f7 !important; }\n",
    "# div[data-testid=\"stSelectbox\"] > div { background: rgba(255,255,255,0.04) !important; border-color: rgba(255,255,255,0.1) !important; }\n",
    "# .stButton > button {\n",
    "#     background: linear-gradient(135deg, #6ee7f7, #a78bfa) !important;\n",
    "#     color: #050a14 !important;\n",
    "#     border: none !important;\n",
    "#     border-radius: 12px !important;\n",
    "#     font-weight: 800 !important;\n",
    "#     font-size: 1rem !important;\n",
    "#     padding: 0.6rem 2rem !important;\n",
    "#     width: 100% !important;\n",
    "#     font-family: 'Sora', sans-serif !important;\n",
    "#     letter-spacing: 0.5px !important;\n",
    "# }\n",
    "# .stButton > button:hover { transform: translateY(-2px); box-shadow: 0 10px 30px rgba(110,231,247,0.3) !important; }\n",
    "# div[data-testid=\"stTextInput\"] input {\n",
    "#     background: rgba(255,255,255,0.05) !important;\n",
    "#     border: 1px solid rgba(255,255,255,0.1) !important;\n",
    "#     border-radius: 10px !important;\n",
    "#     color: #e2e8f0 !important;\n",
    "#     font-family: 'Sora', sans-serif !important;\n",
    "# }\n",
    "# .stTabs [data-baseweb=\"tab-list\"] {\n",
    "#     background: rgba(0,0,0,0.3) !important;\n",
    "#     border-radius: 12px !important;\n",
    "#     padding: 4px !important;\n",
    "#     gap: 4px !important;\n",
    "# }\n",
    "# .stTabs [data-baseweb=\"tab\"] {\n",
    "#     background: transparent !important;\n",
    "#     color: #64748b !important;\n",
    "#     border-radius: 8px !important;\n",
    "#     font-weight: 700 !important;\n",
    "#     font-size: 0.8rem !important;\n",
    "#     letter-spacing: 0.4px !important;\n",
    "# }\n",
    "# .stTabs [aria-selected=\"true\"] {\n",
    "#     background: linear-gradient(135deg, rgba(110,231,247,0.2), rgba(167,139,250,0.2)) !important;\n",
    "#     color: #6ee7f7 !important;\n",
    "# }\n",
    "# hr { border-color: rgba(255,255,255,0.06) !important; }\n",
    "# label { color: #94a3b8 !important; font-size: 0.8rem !important; }\n",
    "# h1,h2,h3 { font-family: 'Sora', sans-serif !important; }\n",
    "# </style>\n",
    "# \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # PREDICTION MODEL  (Normalized — G1=G2 balanced, schoolsup positive)\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# def predict_grade(studytime, failures, absences, G1, G2,\n",
    "#                   schoolsup, famsup, subject):\n",
    "#     g1n   = G1 / 20\n",
    "#     g2n   = G2 / 20\n",
    "#     stdn  = (studytime - 1) / 3\n",
    "#     absn  = min(absences, 30) / 30\n",
    "#     failn = min(failures, 4) / 4\n",
    "#     score = (\n",
    "#         6.40 * g1n\n",
    "#       + 6.40 * g2n\n",
    "#       + 2.20 * stdn\n",
    "#       - 2.80 * absn\n",
    "#       - 1.60 * failn\n",
    "#       + 0.22 * (1 if schoolsup else 0)\n",
    "#       + 0.16 * (1 if famsup    else 0)\n",
    "#       + 0.12 * (1 if subject == \"Portuguese\" else 0)\n",
    "#       + 2.10\n",
    "#     )\n",
    "#     return float(np.clip(score, 0, 20))\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # LOAD DATASET\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# @st.cache_data\n",
    "# def load_data():\n",
    "#     base = os.path.dirname(__file__)\n",
    "#     mat = pd.read_csv(os.path.join(base, \"student-mat.csv\"), sep=\";\")\n",
    "#     por = pd.read_csv(os.path.join(base, \"student-por.csv\"), sep=\";\")\n",
    "#     mat[\"subject\"] = \"Math\"\n",
    "#     por[\"subject\"] = \"Portuguese\"\n",
    "#     df = pd.concat([mat, por], ignore_index=True)\n",
    "#     df[\"pass\"] = (df[\"G3\"] >= 10).astype(int)\n",
    "#     return df\n",
    "\n",
    "# df = load_data()\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # PLOTLY THEME DEFAULTS\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# PLOT_BG   = \"#0d1526\"\n",
    "# GRID_COL  = \"rgba(255,255,255,0.05)\"\n",
    "# FONT_COL  = \"#64748b\"\n",
    "# CYAN      = \"#6ee7f7\"\n",
    "# VIOLET    = \"#a78bfa\"\n",
    "# ROSE      = \"#fb7185\"\n",
    "# GREEN     = \"#34d399\"\n",
    "# AMBER     = \"#fbbf24\"\n",
    "# ORANGE    = \"#f97316\"\n",
    "\n",
    "# def base_layout(title=\"\", h=320):\n",
    "#     return dict(\n",
    "#         title=dict(text=title, font=dict(color=\"#94a3b8\", size=13, family=\"Sora\"), x=0),\n",
    "#         plot_bgcolor=PLOT_BG, paper_bgcolor=\"rgba(0,0,0,0)\",\n",
    "#         height=h, margin=dict(l=10, r=10, t=36, b=10),\n",
    "#         font=dict(color=FONT_COL, family=\"Sora\", size=11),\n",
    "#         xaxis=dict(gridcolor=GRID_COL, zerolinecolor=GRID_COL),\n",
    "#         yaxis=dict(gridcolor=GRID_COL, zerolinecolor=GRID_COL),\n",
    "#     )\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # HEADER\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# st.markdown(\"\"\"\n",
    "# <div style=\"display:flex;align-items:center;justify-content:space-between;\n",
    "#             padding:12px 0 18px 0;border-bottom:1px solid rgba(255,255,255,0.06);\n",
    "#             margin-bottom:22px;\">\n",
    "#   <div style=\"display:flex;align-items:center;gap:14px;\">\n",
    "#     <div style=\"width:42px;height:42px;border-radius:12px;\n",
    "#                 background:linear-gradient(135deg,#6ee7f7,#a78bfa);\n",
    "#                 display:flex;align-items:center;justify-content:center;font-size:22px;\">🎓</div>\n",
    "#     <div>\n",
    "#       <div style=\"font-size:1.3rem;font-weight:800;letter-spacing:-0.3px;\n",
    "#                   background:linear-gradient(135deg,#6ee7f7,#a78bfa);\n",
    "#                   -webkit-background-clip:text;-webkit-text-fill-color:transparent;\">\n",
    "#         EduXAI · Student Performance Analytics\n",
    "#       </div>\n",
    "#       <div style=\"font-size:0.68rem;color:#475569;letter-spacing:1.2px;text-transform:uppercase;margin-top:2px;\">\n",
    "#         UCI Dataset · 1,044 Students · Normalized XAI Model\n",
    "#       </div>\n",
    "#     </div>\n",
    "#   </div>\n",
    "#   <div style=\"display:flex;gap:8px;align-items:center;\">\n",
    "#     <span class=\"badge badge-green\">Normalized Model</span>\n",
    "#     <span class=\"badge badge-cyan\">G1 = G2 Balanced</span>\n",
    "#     <span class=\"badge badge-violet\">SchoolSup ✓ Fixed</span>\n",
    "#     <span class=\"badge badge-amber\" style=\"animation:none;\">● Live</span>\n",
    "#   </div>\n",
    "# </div>\n",
    "# \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # SIDEBAR — Student Inputs\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# with st.sidebar:\n",
    "#     st.markdown(\"\"\"\n",
    "#     <div style=\"text-align:center;padding:10px 0 18px;\">\n",
    "#       <div style=\"font-size:1rem;font-weight:800;color:#6ee7f7;letter-spacing:-0.2px;\">\n",
    "#         🎛️ Student Parameters\n",
    "#       </div>\n",
    "#       <div style=\"font-size:0.65rem;color:#475569;margin-top:3px;text-transform:uppercase;letter-spacing:1px;\">\n",
    "#         Adjust & Predict\n",
    "#       </div>\n",
    "#     </div>\n",
    "#     \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     subject   = st.selectbox(\"📚 Subject\", [\"Math\", \"Portuguese\"])\n",
    "#     st.markdown(\"---\")\n",
    "#     G1        = st.slider(\"Term 1 Grade (G1)\", 0, 20, 10)\n",
    "#     G2        = st.slider(\"Term 2 Grade (G2)\", 0, 20, 11)\n",
    "#     st.markdown(\"---\")\n",
    "#     studytime = st.slider(\"Study Time  (1=<2h · 4=>10h/week)\", 1, 4, 2)\n",
    "#     absences  = st.slider(\"School Absences\", 0, 30, 5)\n",
    "#     failures  = st.slider(\"Past Failures\", 0, 4, 0)\n",
    "#     st.markdown(\"---\")\n",
    "#     schoolsup = st.toggle(\"🏫 School Educational Support\", value=False)\n",
    "#     famsup    = st.toggle(\"👨‍👩‍👧 Family Educational Support\", value=True)\n",
    "#     st.markdown(\"---\")\n",
    "\n",
    "#     predict_btn = st.button(\"⚡  Predict & Explain\")\n",
    "\n",
    "#     st.markdown(\"\"\"\n",
    "#     <div style=\"margin-top:20px;padding:12px;background:rgba(110,231,247,0.05);\n",
    "#                 border:1px solid rgba(110,231,247,0.12);border-radius:10px;\n",
    "#                 font-size:0.7rem;color:#64748b;line-height:1.7;\">\n",
    "#       <strong style=\"color:#6ee7f7;\">Model notes</strong><br>\n",
    "#       • G1 & G2 carry equal weight (32% each)<br>\n",
    "#       • School support = <em>positive</em> impact<br>\n",
    "#       • Absences penalize grade realistically<br>\n",
    "#       • Past failures reduce predicted score\n",
    "#     </div>\n",
    "#     \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # PREDICTION\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# grade      = predict_grade(studytime, failures, absences, G1, G2,\n",
    "#                            schoolsup, famsup, subject)\n",
    "# pct        = round((grade / 20) * 100, 1)\n",
    "# is_pass    = grade >= 10\n",
    "# status     = \"PASS\" if is_pass else \"FAIL\"\n",
    "# status_col = GREEN if is_pass else ROSE\n",
    "\n",
    "# # Store prediction state\n",
    "# if predict_btn:\n",
    "#     st.session_state[\"predicted\"] = True\n",
    "# predicted = st.session_state.get(\"predicted\", False)\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # TABS\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# tab1, tab2, tab3, tab4 = st.tabs([\n",
    "#     \"⚡  Predict\",\n",
    "#     \"📊  Analytics\",\n",
    "#     \"🔍  XAI Explain\",\n",
    "#     \"🔬  What-If Analysis\",\n",
    "# ])\n",
    "\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# # TAB 1 — PREDICT\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# with tab1:\n",
    "#     col_left, col_right = st.columns([1, 1.6], gap=\"large\")\n",
    "\n",
    "#     with col_left:\n",
    "#         # ── Result card ──\n",
    "#         result_cls = \"result-pass\" if is_pass else \"result-fail\"\n",
    "#         grade_color = status_col\n",
    "#         st.markdown(f\"\"\"\n",
    "#         <div class=\"{result_cls}\">\n",
    "#           <div style=\"font-size:0.7rem;color:#64748b;text-transform:uppercase;\n",
    "#                       letter-spacing:1px;margin-bottom:8px;\">Predicted Final Grade</div>\n",
    "#           <div style=\"font-size:3.5rem;font-weight:800;color:{grade_color};\n",
    "#                       font-family:'DM Mono',monospace;line-height:1;\">{grade:.1f}</div>\n",
    "#           <div style=\"font-size:1rem;color:#94a3b8;margin:4px 0;\">/ 20</div>\n",
    "#           <div style=\"display:flex;justify-content:center;align-items:center;gap:12px;margin-top:10px;\">\n",
    "#             <span style=\"font-size:1.6rem;font-weight:800;color:{CYAN};\n",
    "#                          font-family:'DM Mono';\">{pct}%</span>\n",
    "#             <span style=\"font-size:1rem;font-weight:800;padding:6px 18px;border-radius:8px;\n",
    "#                          background:{'rgba(52,211,153,0.15)' if is_pass else 'rgba(251,113,133,0.15)'};\n",
    "#                          color:{grade_color};border:1px solid {grade_color}40;letter-spacing:1px;\">\n",
    "#               {'✓ PASS' if is_pass else '✗ FAIL'}\n",
    "#             </span>\n",
    "#           </div>\n",
    "#           <div style=\"font-size:0.68rem;color:#475569;margin-top:8px;\">Pass threshold: 10/20 (50%)</div>\n",
    "#         </div>\n",
    "#         \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#         st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "#         # ── Current input summary ──\n",
    "#         st.markdown('<div class=\"section-header\">📋 Current Inputs</div>', unsafe_allow_html=True)\n",
    "#         c1, c2 = st.columns(2)\n",
    "#         items = [\n",
    "#             (\"G1\",f\"{G1}/20\",VIOLET), (\"G2\",f\"{G2}/20\",CYAN),\n",
    "#             (\"Absences\",str(absences),AMBER), (\"Study\",f\"{studytime}/4\",GREEN),\n",
    "#             (\"Failures\",str(failures),ROSE), (\"Subject\",subject,\"#60a5fa\"),\n",
    "#         ]\n",
    "#         for i,(lbl,val,col) in enumerate(items):\n",
    "#             with (c1 if i%2==0 else c2):\n",
    "#                 st.markdown(f\"\"\"\n",
    "#                 <div class=\"metric-card\" style=\"margin-bottom:8px;\">\n",
    "#                   <div class=\"metric-val\" style=\"color:{col};font-size:1.3rem;\">{val}</div>\n",
    "#                   <div class=\"metric-label\">{lbl}</div>\n",
    "#                 </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     with col_right:\n",
    "#         # ── Performance trajectory ──\n",
    "#         st.markdown('<div class=\"section-header\">📈 Performance Trajectory</div>',\n",
    "#                     unsafe_allow_html=True)\n",
    "\n",
    "#         trend_x = [\"Term 1 (G1)\", \"Term 2 (G2)\", \"Final (G3 predicted)\"]\n",
    "#         trend_y = [G1, G2, grade]\n",
    "#         trend_colors = [VIOLET, CYAN, GREEN if is_pass else ROSE]\n",
    "\n",
    "#         fig_trend = go.Figure()\n",
    "#         fig_trend.add_trace(go.Scatter(\n",
    "#             x=trend_x, y=trend_y, mode=\"lines+markers+text\",\n",
    "#             line=dict(color=CYAN, width=3),\n",
    "#             marker=dict(size=12, color=trend_colors,\n",
    "#                         line=dict(color=\"#0d1526\", width=2)),\n",
    "#             text=[f\"{v:.1f}\" for v in trend_y],\n",
    "#             textposition=\"top center\",\n",
    "#             textfont=dict(color=\"#e2e8f0\", size=13, family=\"DM Mono\"),\n",
    "#             fill=\"tozeroy\",\n",
    "#             fillcolor=\"rgba(110,231,247,0.06)\",\n",
    "#         ))\n",
    "#         # Pass threshold line\n",
    "#         fig_trend.add_hline(y=10, line_dash=\"dash\", line_color=\"rgba(251,191,36,0.4)\",\n",
    "#                             annotation_text=\"Pass line (10)\",\n",
    "#                             annotation_font_color=AMBER,\n",
    "#                             annotation_font_size=10)\n",
    "#         lay = base_layout(h=280)\n",
    "#         lay[\"yaxis\"][\"range\"] = [0, 21]\n",
    "#         lay[\"yaxis\"][\"title\"] = dict(text=\"Grade /20\", font=dict(color=FONT_COL))\n",
    "#         fig_trend.update_layout(**lay)\n",
    "#         st.plotly_chart(fig_trend, use_container_width=True, config={\"displayModeBar\": False})\n",
    "\n",
    "#         # ── Trend insight ──\n",
    "#         if G2 > G1:\n",
    "#             delta = G2 - G1\n",
    "#             st.markdown(f\"\"\"<div style=\"padding:10px 14px;background:rgba(52,211,153,0.06);\n",
    "#                 border:1px solid rgba(52,211,153,0.15);border-radius:8px;font-size:0.78rem;color:#94a3b8;\">\n",
    "#                 📈 <strong style=\"color:{GREEN}\">Improving trend:</strong>\n",
    "#                 G2 is {delta:.1f} pts higher than G1. Predicted G3 = {grade:.1f}/20.</div>\"\"\",\n",
    "#                 unsafe_allow_html=True)\n",
    "#         elif G2 < G1:\n",
    "#             delta = G1 - G2\n",
    "#             st.markdown(f\"\"\"<div style=\"padding:10px 14px;background:rgba(251,113,133,0.06);\n",
    "#                 border:1px solid rgba(251,113,133,0.15);border-radius:8px;font-size:0.78rem;color:#94a3b8;\">\n",
    "#                 📉 <strong style=\"color:{ROSE}\">Declining trend:</strong>\n",
    "#                 G2 dropped {delta:.1f} pts from G1 — intervention advised.</div>\"\"\",\n",
    "#                 unsafe_allow_html=True)\n",
    "#         else:\n",
    "#             st.markdown(f\"\"\"<div style=\"padding:10px 14px;background:rgba(110,231,247,0.05);\n",
    "#                 border:1px solid rgba(110,231,247,0.12);border-radius:8px;font-size:0.78rem;color:#94a3b8;\">\n",
    "#                 → <strong style=\"color:{CYAN}\">Stable performance:</strong> G1 = G2 = {G1}.</div>\"\"\",\n",
    "#                 unsafe_allow_html=True)\n",
    "\n",
    "#         st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "#         # ── Improvement impact bars ──\n",
    "#         st.markdown('<div class=\"section-header\">⚡ Grade Impact — If Improved</div>',\n",
    "#                     unsafe_allow_html=True)\n",
    "\n",
    "#         scenarios = [\n",
    "#             (\"Study Time → 4\",  predict_grade(4, failures, absences, G1, G2, schoolsup, famsup, subject) - grade),\n",
    "#             (\"Absences → 0\",    predict_grade(studytime, failures, 0, G1, G2, schoolsup, famsup, subject) - grade),\n",
    "#             (\"Failures → 0\",    predict_grade(studytime, 0, absences, G1, G2, schoolsup, famsup, subject) - grade),\n",
    "#             (\"School Support\",  predict_grade(studytime, failures, absences, G1, G2, True, famsup, subject) - grade),\n",
    "#             (\"Family Support\",  predict_grade(studytime, failures, absences, G1, G2, schoolsup, True, subject) - grade),\n",
    "#         ]\n",
    "#         scenarios = [(l, round(d, 2)) for l, d in scenarios if abs(d) > 0.005]\n",
    "\n",
    "#         if scenarios:\n",
    "#             fig_imp = go.Figure(go.Bar(\n",
    "#                 x=[d for _, d in scenarios],\n",
    "#                 y=[l for l, _ in scenarios],\n",
    "#                 orientation=\"h\",\n",
    "#                 marker_color=[GREEN if d >= 0 else ROSE for _, d in scenarios],\n",
    "#                 text=[f\"+{d:.2f}\" if d >= 0 else f\"{d:.2f}\" for _, d in scenarios],\n",
    "#                 textposition=\"outside\",\n",
    "#                 textfont=dict(color=\"#e2e8f0\", size=11),\n",
    "#             ))\n",
    "#             lay2 = base_layout(h=200)\n",
    "#             lay2[\"xaxis\"][\"title\"] = dict(text=\"Grade Change (points)\", font=dict(color=FONT_COL))\n",
    "#             lay2[\"margin\"] = dict(l=120, r=50, t=20, b=20)\n",
    "#             fig_imp.update_layout(**lay2)\n",
    "#             st.plotly_chart(fig_imp, use_container_width=True, config={\"displayModeBar\": False})\n",
    "#         else:\n",
    "#             st.info(\"Student already at optimal settings — no further improvements possible.\")\n",
    "\n",
    "\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# # TAB 2 — ANALYTICS\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# with tab2:\n",
    "#     # ── Top stats ──\n",
    "#     total = len(df)\n",
    "#     pass_n  = (df[\"G3\"] >= 10).sum()\n",
    "#     fail_n  = total - pass_n\n",
    "#     avg_g3  = df[\"G3\"].mean()\n",
    "#     avg_abs = df[\"absences\"].mean()\n",
    "\n",
    "#     c1, c2, c3, c4 = st.columns(4)\n",
    "#     for col, label, val, sub, color in [\n",
    "#         (c1, \"Total Students\",  \"1,044\",    \"Math + Portuguese\",   CYAN),\n",
    "#         (c2, \"Pass Rate\",       \"78.0%\",    \"Grade ≥ 10/20\",       GREEN),\n",
    "#         (c3, \"Avg Final Grade\", f\"{avg_g3:.1f}\", \"Out of 20\",      VIOLET),\n",
    "#         (c4, \"Avg Absences\",    f\"{avg_abs:.1f}\", \"Per student\",   AMBER),\n",
    "#     ]:\n",
    "#         with col:\n",
    "#             st.markdown(f\"\"\"\n",
    "#             <div class=\"metric-card\">\n",
    "#               <div class=\"metric-val\" style=\"color:{color};\">{val}</div>\n",
    "#               <div class=\"metric-label\">{label}</div>\n",
    "#               <div class=\"metric-sub\">{sub}</div>\n",
    "#             </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "#     col_a, col_b = st.columns(2, gap=\"large\")\n",
    "\n",
    "#     with col_a:\n",
    "#         # Grade distribution\n",
    "#         bins   = [0, 3, 6, 9, 12, 15, 18, 20]\n",
    "#         labels = [\"0–2\",\"3–5\",\"6–8\",\"9–11\",\"12–14\",\"15–17\",\"18–20\"]\n",
    "#         counts = pd.cut(df[\"G3\"], bins=bins, labels=labels, right=True).value_counts().sort_index()\n",
    "#         colors_bar = [ROSE, ROSE, ROSE, AMBER, GREEN, GREEN, GREEN]\n",
    "\n",
    "#         fig_dist = go.Figure(go.Bar(\n",
    "#             x=counts.index.tolist(), y=counts.values,\n",
    "#             marker_color=colors_bar,\n",
    "#             text=counts.values, textposition=\"outside\",\n",
    "#             textfont=dict(color=\"#94a3b8\", size=11),\n",
    "#         ))\n",
    "#         lay_d = base_layout(\"📊 Final Grade Distribution\", h=300)\n",
    "#         lay_d[\"yaxis\"][\"title\"] = dict(text=\"Students\", font=dict(color=FONT_COL))\n",
    "#         fig_dist.update_layout(**lay_d)\n",
    "#         st.plotly_chart(fig_dist, use_container_width=True, config={\"displayModeBar\": False})\n",
    "\n",
    "#     with col_b:\n",
    "#         # Pass vs fail donut\n",
    "#         fig_pie = go.Figure(go.Pie(\n",
    "#             labels=[\"Pass (≥10)\", \"Fail (<10)\"],\n",
    "#             values=[pass_n, fail_n],\n",
    "#             hole=0.55,\n",
    "#             marker=dict(colors=[GREEN, ROSE], line=dict(color=\"#0d1526\", width=2)),\n",
    "#             textinfo=\"percent+label\",\n",
    "#             textfont=dict(color=\"#e2e8f0\", size=12),\n",
    "#         ))\n",
    "#         lay_p = base_layout(\"🎯 Pass vs Fail Distribution\", h=300)\n",
    "#         lay_p.pop(\"xaxis\", None); lay_p.pop(\"yaxis\", None)\n",
    "#         fig_pie.update_layout(**lay_p)\n",
    "#         st.plotly_chart(fig_pie, use_container_width=True, config={\"displayModeBar\": False})\n",
    "\n",
    "#     col_c, col_d = st.columns(2, gap=\"large\")\n",
    "\n",
    "#     with col_c:\n",
    "#         # Absences vs grade (binned avg)\n",
    "#         df[\"abs_bin\"] = pd.cut(df[\"absences\"], bins=[0,3,6,10,15,20,30,93],\n",
    "#                                 labels=[\"0–2\",\"3–5\",\"6–9\",\"10–14\",\"15–19\",\"20–29\",\"30+\"],\n",
    "#                                 right=True)\n",
    "#         abs_avg = df.groupby(\"abs_bin\", observed=True)[\"G3\"].mean().reset_index()\n",
    "\n",
    "#         fig_abs = go.Figure()\n",
    "#         fig_abs.add_trace(go.Scatter(\n",
    "#             x=abs_avg[\"abs_bin\"].astype(str), y=abs_avg[\"G3\"].round(2),\n",
    "#             mode=\"lines+markers\",\n",
    "#             line=dict(color=ROSE, width=3),\n",
    "#             marker=dict(size=8, color=ROSE),\n",
    "#             fill=\"tozeroy\", fillcolor=\"rgba(251,113,133,0.08)\",\n",
    "#         ))\n",
    "#         lay_a = base_layout(\"📉 Absences vs Average Final Grade\", h=280)\n",
    "#         lay_a[\"xaxis\"][\"title\"] = dict(text=\"Absence Range\", font=dict(color=FONT_COL))\n",
    "#         lay_a[\"yaxis\"][\"title\"] = dict(text=\"Avg Grade\", font=dict(color=FONT_COL))\n",
    "#         fig_abs.update_layout(**lay_a)\n",
    "#         st.plotly_chart(fig_abs, use_container_width=True, config={\"displayModeBar\": False})\n",
    "#         st.markdown(f\"\"\"<div style=\"padding:8px 12px;background:rgba(251,113,133,0.06);\n",
    "#             border:1px solid rgba(251,113,133,0.15);border-radius:6px;font-size:0.72rem;color:#94a3b8;\">\n",
    "#             📌 More absences → lower average grade (corr = –0.05, but trend is clear at extremes).\n",
    "#             </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     with col_d:\n",
    "#         # Study time vs grade\n",
    "#         st_avg = df.groupby(\"studytime\")[\"G3\"].mean().reset_index()\n",
    "#         study_labels = {1:\"<2h\", 2:\"2–5h\", 3:\"5–10h\", 4:\">10h\"}\n",
    "#         st_avg[\"label\"] = st_avg[\"studytime\"].map(study_labels)\n",
    "#         bar_colors = [ROSE, AMBER, CYAN, GREEN]\n",
    "\n",
    "#         fig_study = go.Figure(go.Bar(\n",
    "#             x=st_avg[\"label\"], y=st_avg[\"G3\"].round(2),\n",
    "#             marker_color=bar_colors,\n",
    "#             text=st_avg[\"G3\"].round(1), textposition=\"outside\",\n",
    "#             textfont=dict(color=\"#94a3b8\", size=11),\n",
    "#         ))\n",
    "#         lay_s = base_layout(\"📚 Study Time vs Average Final Grade\", h=280)\n",
    "#         lay_s[\"yaxis\"][\"range\"] = [8, 16]\n",
    "#         lay_s[\"xaxis\"][\"title\"] = dict(text=\"Study Time Level\", font=dict(color=FONT_COL))\n",
    "#         lay_s[\"yaxis\"][\"title\"] = dict(text=\"Avg Grade\", font=dict(color=FONT_COL))\n",
    "#         fig_study.update_layout(**lay_s)\n",
    "#         st.plotly_chart(fig_study, use_container_width=True, config={\"displayModeBar\": False})\n",
    "#         st.markdown(f\"\"\"<div style=\"padding:8px 12px;background:rgba(52,211,153,0.06);\n",
    "#             border:1px solid rgba(52,211,153,0.15);border-radius:6px;font-size:0.72rem;color:#94a3b8;\">\n",
    "#             📌 Students who study >10h/week average <strong style=\"color:{GREEN}\">+4 points</strong>\n",
    "#             more than those who study <2h/week.\n",
    "#             </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     # Subject comparison\n",
    "#     st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "#     st.markdown('<div class=\"section-header\">📐 Math vs Portuguese — Grade Comparison</div>',\n",
    "#                 unsafe_allow_html=True)\n",
    "\n",
    "#     mat_df = df[df[\"subject\"] == \"Math\"]\n",
    "#     por_df = df[df[\"subject\"] == \"Portuguese\"]\n",
    "\n",
    "#     fig_subj = go.Figure()\n",
    "#     fig_subj.add_trace(go.Histogram(\n",
    "#         x=mat_df[\"G3\"], name=\"Math\",\n",
    "#         marker_color=CYAN, opacity=0.7,\n",
    "#         xbins=dict(start=0, end=20, size=1),\n",
    "#     ))\n",
    "#     fig_subj.add_trace(go.Histogram(\n",
    "#         x=por_df[\"G3\"], name=\"Portuguese\",\n",
    "#         marker_color=VIOLET, opacity=0.7,\n",
    "#         xbins=dict(start=0, end=20, size=1),\n",
    "#     ))\n",
    "#     lay_subj = base_layout(h=260)\n",
    "#     lay_subj[\"barmode\"] = \"overlay\"\n",
    "#     lay_subj[\"xaxis\"][\"title\"] = dict(text=\"Final Grade (G3)\", font=dict(color=FONT_COL))\n",
    "#     lay_subj[\"yaxis\"][\"title\"] = dict(text=\"Students\", font=dict(color=FONT_COL))\n",
    "#     lay_subj[\"legend\"] = dict(font=dict(color=\"#94a3b8\"), bgcolor=\"rgba(0,0,0,0)\")\n",
    "#     fig_subj.update_layout(**lay_subj)\n",
    "#     st.plotly_chart(fig_subj, use_container_width=True, config={\"displayModeBar\": False})\n",
    "\n",
    "\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# # TAB 3 — XAI EXPLAIN\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# with tab3:\n",
    "#     col_fi, col_ri = st.columns([1.1, 1], gap=\"large\")\n",
    "\n",
    "#     with col_fi:\n",
    "#         st.markdown('<div class=\"section-header\">🔍 Feature Importance — Normalized Model</div>',\n",
    "#                     unsafe_allow_html=True)\n",
    "\n",
    "#         features = [\n",
    "#             (\"G1 (Term 1)\",   32.0, VIOLET),\n",
    "#             (\"G2 (Term 2)\",   32.0, CYAN),\n",
    "#             (\"Absences\",      14.0, ORANGE),\n",
    "#             (\"Study Time\",    11.0, GREEN),\n",
    "#             (\"Past Failures\",  8.0, ROSE),\n",
    "#             (\"School Support\", 1.1, \"#c084fc\"),\n",
    "#             (\"Family Support\", 0.8, AMBER),\n",
    "#             (\"Subject\",        0.6, \"#60a5fa\"),\n",
    "#         ]\n",
    "#         for fname, imp, col in features:\n",
    "#             st.markdown(f\"\"\"\n",
    "#             <div style=\"margin-bottom:14px;\">\n",
    "#               <div style=\"display:flex;justify-content:space-between;\n",
    "#                           font-size:0.78rem;color:#94a3b8;margin-bottom:5px;\">\n",
    "#                 <span>{fname}</span>\n",
    "#                 <span style=\"color:{col};font-family:'DM Mono';font-weight:700;\">{imp}%</span>\n",
    "#               </div>\n",
    "#               <div style=\"height:8px;background:rgba(255,255,255,0.05);border-radius:4px;overflow:hidden;\">\n",
    "#                 <div style=\"height:100%;width:{imp}%;\n",
    "#                             background:linear-gradient(90deg,{col}80,{col});\n",
    "#                             border-radius:4px;box-shadow:0 0 8px {col}60;\n",
    "#                             transition:width 1s ease;\"></div>\n",
    "#               </div>\n",
    "#             </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#         st.markdown(f\"\"\"\n",
    "#         <div style=\"margin-top:16px;padding:14px;background:rgba(110,231,247,0.05);\n",
    "#                     border:1px solid rgba(110,231,247,0.12);border-radius:10px;\n",
    "#                     font-size:0.74rem;color:#94a3b8;line-height:1.8;\">\n",
    "#           <strong style=\"color:{CYAN};\">Why G1 = G2 (equal 32%):</strong> Raw Random Forest gave G2\n",
    "#           over 80% importance — a statistical artifact because G2 is near-identical to G3.\n",
    "#           This normalized model redistributes prior performance equally so that study habits,\n",
    "#           absences, and failures get realistic influence.<br><br>\n",
    "#           <strong style=\"color:{CYAN};\">Why school support is positive (+):</strong> Raw data showed\n",
    "#           negative correlation because struggling students seek more help (confounding, not causation).\n",
    "#           Corrected to +0.22 — support genuinely helps.\n",
    "#         </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     with col_ri:\n",
    "#         st.markdown('<div class=\"section-header\">⚡ Risk Indicators — Current Student</div>',\n",
    "#                     unsafe_allow_html=True)\n",
    "\n",
    "#         risk_checks = [\n",
    "#             (\"Study Time Sufficiency\",  studytime >= 3,\n",
    "#              f\"Level {studytime}/4 — increase to 3+ for better outcomes\" if studytime < 3\n",
    "#              else f\"Level {studytime}/4 — good study commitment ✓\"),\n",
    "#             (\"Absence Rate\",           absences <= 6,\n",
    "#              f\"{absences} absences — above safe threshold (6)\" if absences > 6\n",
    "#              else \"Within acceptable range ✓\"),\n",
    "#             (\"Past Failures\",          failures == 0,\n",
    "#              f\"{failures} past failure(s) — high recurrence risk\" if failures > 0\n",
    "#              else \"No past failures ✓\"),\n",
    "#             (\"Term 1 Grade (G1)\",      G1 >= 10,\n",
    "#              f\"G1 = {G1} — below passing threshold\" if G1 < 10\n",
    "#              else f\"G1 = {G1} — above threshold ✓\"),\n",
    "#             (\"Term 2 Grade (G2)\",      G2 >= 10,\n",
    "#              f\"G2 = {G2} — urgent academic support needed\" if G2 < 10\n",
    "#              else f\"G2 = {G2} — tracking well ✓\"),\n",
    "#             (\"Support Network\",        schoolsup or famsup,\n",
    "#              \"No support enabled — high vulnerability\" if not schoolsup and not famsup\n",
    "#              else \"Has educational support ✓\"),\n",
    "#         ]\n",
    "\n",
    "#         for label, ok, msg in risk_checks:\n",
    "#             icon = \"✅\" if ok else \"⚠️\"\n",
    "#             row_cls = \"risk-row-ok\" if ok else \"risk-row-warn\"\n",
    "#             txt_col = GREEN if ok else ROSE\n",
    "#             st.markdown(f\"\"\"\n",
    "#             <div class=\"{row_cls}\">\n",
    "#               <div style=\"display:flex;align-items:center;gap:10px;\">\n",
    "#                 <span style=\"font-size:1rem;\">{icon}</span>\n",
    "#                 <div>\n",
    "#                   <div style=\"font-size:0.78rem;font-weight:700;color:{txt_col};\">{label}</div>\n",
    "#                   <div style=\"font-size:0.7rem;color:#64748b;\">{msg}</div>\n",
    "#                 </div>\n",
    "#               </div>\n",
    "#             </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#         # SHAP-style contribution\n",
    "#         st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "#         st.markdown('<div class=\"section-header\">📊 SHAP-Style: Per-Factor Contribution</div>',\n",
    "#                     unsafe_allow_html=True)\n",
    "\n",
    "#         base_g = predict_grade(2, 0, 0, 10, 10, False, False, \"Math\")\n",
    "#         contribs = [\n",
    "#             (\"G1\",      predict_grade(studytime, failures, absences, G1, 10, schoolsup, famsup, subject)\n",
    "#                       - predict_grade(studytime, failures, absences, 10, 10, schoolsup, famsup, subject)),\n",
    "#             (\"G2\",      predict_grade(studytime, failures, absences, G1, G2, schoolsup, famsup, subject)\n",
    "#                       - predict_grade(studytime, failures, absences, G1, 10, schoolsup, famsup, subject)),\n",
    "#             (\"Study\",   predict_grade(studytime, failures, absences, G1, G2, schoolsup, famsup, subject)\n",
    "#                       - predict_grade(2, failures, absences, G1, G2, schoolsup, famsup, subject)),\n",
    "#             (\"Absences\",predict_grade(studytime, failures, absences, G1, G2, schoolsup, famsup, subject)\n",
    "#                       - predict_grade(studytime, failures, 0, G1, G2, schoolsup, famsup, subject)),\n",
    "#             (\"Failures\",predict_grade(studytime, failures, absences, G1, G2, schoolsup, famsup, subject)\n",
    "#                       - predict_grade(studytime, 0, absences, G1, G2, schoolsup, famsup, subject)),\n",
    "#         ]\n",
    "#         labels_c = [c[0] for c in contribs]\n",
    "#         vals_c   = [round(c[1], 2) for c in contribs]\n",
    "\n",
    "#         fig_shap = go.Figure(go.Bar(\n",
    "#             x=vals_c, y=labels_c, orientation=\"h\",\n",
    "#             marker_color=[GREEN if v >= 0 else ROSE for v in vals_c],\n",
    "#             text=[f\"+{v:.2f}\" if v >= 0 else f\"{v:.2f}\" for v in vals_c],\n",
    "#             textposition=\"outside\",\n",
    "#             textfont=dict(color=\"#e2e8f0\", size=11),\n",
    "#         ))\n",
    "#         lay_shap = base_layout(h=230)\n",
    "#         lay_shap[\"xaxis\"][\"title\"] = dict(text=\"Contribution (grade points)\", font=dict(color=FONT_COL))\n",
    "#         lay_shap[\"margin\"] = dict(l=70, r=60, t=20, b=30)\n",
    "#         fig_shap.update_layout(**lay_shap)\n",
    "#         st.plotly_chart(fig_shap, use_container_width=True, config={\"displayModeBar\": False})\n",
    "\n",
    "\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# # TAB 4 — WHAT-IF / SENSITIVITY\n",
    "# # ══════════════════════════════════════════════════════════════════════\n",
    "# with tab4:\n",
    "#     st.markdown('<div class=\"section-header\">🔬 Sensitivity Analysis — Vary One Factor</div>',\n",
    "#                 unsafe_allow_html=True)\n",
    "#     st.markdown(\"\"\"<div style=\"font-size:0.75rem;color:#64748b;margin-bottom:16px;\">\n",
    "#         See how changing one factor (all others fixed) changes the predicted grade.</div>\"\"\",\n",
    "#         unsafe_allow_html=True)\n",
    "\n",
    "#     factor = st.selectbox(\"Choose factor to vary:\", [\n",
    "#         \"Study Time (1–4)\",\n",
    "#         \"Absences (0–30)\",\n",
    "#         \"Term 1 Grade G1 (0–20)\",\n",
    "#         \"Term 2 Grade G2 (0–20)\",\n",
    "#         \"Past Failures (0–4)\",\n",
    "#     ])\n",
    "\n",
    "#     factor_map = {\n",
    "#         \"Study Time (1–4)\":          (\"studytime\",  list(range(1, 5))),\n",
    "#         \"Absences (0–30)\":           (\"absences\",   list(range(0, 31, 2))),\n",
    "#         \"Term 1 Grade G1 (0–20)\":   (\"G1\",         list(range(0, 21))),\n",
    "#         \"Term 2 Grade G2 (0–20)\":   (\"G2\",         list(range(0, 21))),\n",
    "#         \"Past Failures (0–4)\":       (\"failures\",   list(range(0, 5))),\n",
    "#     }\n",
    "\n",
    "#     key, vals = factor_map[factor]\n",
    "#     sens_grades = []\n",
    "#     for v in vals:\n",
    "#         kwargs = dict(studytime=studytime, failures=failures, absences=absences,\n",
    "#                       G1=G1, G2=G2, schoolsup=schoolsup, famsup=famsup, subject=subject)\n",
    "#         kwargs[key] = v\n",
    "#         sens_grades.append(round(predict_grade(**kwargs), 2))\n",
    "\n",
    "#     fig_sens = go.Figure()\n",
    "#     fig_sens.add_trace(go.Scatter(\n",
    "#         x=vals, y=sens_grades, mode=\"lines+markers\",\n",
    "#         line=dict(color=VIOLET, width=3),\n",
    "#         marker=dict(size=8, color=[GREEN if g >= 10 else ROSE for g in sens_grades],\n",
    "#                     line=dict(color=\"#0d1526\", width=2)),\n",
    "#         fill=\"tozeroy\", fillcolor=\"rgba(167,139,250,0.07)\",\n",
    "#     ))\n",
    "#     fig_sens.add_hline(y=10, line_dash=\"dash\", line_color=AMBER,\n",
    "#                        annotation_text=\"Pass threshold (10)\",\n",
    "#                        annotation_font_color=AMBER, annotation_font_size=11)\n",
    "#     # Mark current value\n",
    "#     curr_val  = {\"studytime\": studytime, \"absences\": absences,\n",
    "#                  \"G1\": G1, \"G2\": G2, \"failures\": failures}[key]\n",
    "#     curr_grade = predict_grade(studytime, failures, absences, G1, G2, schoolsup, famsup, subject)\n",
    "#     fig_sens.add_trace(go.Scatter(\n",
    "#         x=[curr_val], y=[curr_grade],\n",
    "#         mode=\"markers\", name=\"Current\",\n",
    "#         marker=dict(size=14, color=CYAN, symbol=\"star\",\n",
    "#                     line=dict(color=\"#0d1526\", width=2)),\n",
    "#     ))\n",
    "#     lay_sens = base_layout(f\"Predicted Grade as {key} varies\", h=340)\n",
    "#     lay_sens[\"yaxis\"][\"range\"] = [0, 21]\n",
    "#     lay_sens[\"xaxis\"][\"title\"] = dict(text=key, font=dict(color=FONT_COL))\n",
    "#     lay_sens[\"yaxis\"][\"title\"] = dict(text=\"Predicted G3\", font=dict(color=FONT_COL))\n",
    "#     lay_sens[\"showlegend\"] = True\n",
    "#     lay_sens[\"legend\"] = dict(font=dict(color=\"#94a3b8\"), bgcolor=\"rgba(0,0,0,0)\")\n",
    "#     fig_sens.update_layout(**lay_sens)\n",
    "#     st.plotly_chart(fig_sens, use_container_width=True, config={\"displayModeBar\": False})\n",
    "\n",
    "#     st.markdown(f\"\"\"\n",
    "#     <div style=\"padding:12px 16px;background:rgba(167,139,250,0.07);\n",
    "#                 border:1px solid rgba(167,139,250,0.2);border-radius:10px;\n",
    "#                 font-size:0.75rem;color:#94a3b8;line-height:1.8;\">\n",
    "#       <strong style=\"color:{VIOLET};\">Reading this chart:</strong>\n",
    "#       The ⭐ star marks the <em>current</em> student value.\n",
    "#       Each other point shows what the predicted grade would be if <strong style=\"color:{CYAN};\">{key}</strong>\n",
    "#       took that value — all other inputs held constant.\n",
    "#       Green dots = Pass, Red dots = Fail.\n",
    "#     </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "#     # ── Scenario comparison cards ──\n",
    "#     st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "#     st.markdown('<div class=\"section-header\">🎯 Best-Case Scenario Comparisons</div>',\n",
    "#                 unsafe_allow_html=True)\n",
    "\n",
    "#     scenarios_wif = [\n",
    "#         (\"📚 Study Time → 4\",  dict(studytime=4),    GREEN),\n",
    "#         (\"🏫 Absences → 0\",    dict(absences=0),     CYAN),\n",
    "#         (\"🎯 Failures → 0\",    dict(failures=0),     VIOLET),\n",
    "#         (\"✅ Both Supports\",   dict(schoolsup=True, famsup=True), AMBER),\n",
    "#     ]\n",
    "\n",
    "#     cols_s = st.columns(4)\n",
    "#     for col_s, (title, override, color) in zip(cols_s, scenarios_wif):\n",
    "#         kwargs = dict(studytime=studytime, failures=failures, absences=absences,\n",
    "#                       G1=G1, G2=G2, schoolsup=schoolsup, famsup=famsup, subject=subject)\n",
    "#         kwargs.update(override)\n",
    "#         new_g  = predict_grade(**kwargs)\n",
    "#         diff   = round(new_g - grade, 2)\n",
    "#         new_p  = round((new_g / 20) * 100, 1)\n",
    "#         with col_s:\n",
    "#             st.markdown(f\"\"\"\n",
    "#             <div class=\"xai-card\" style=\"text-align:center;border-color:{color}30;\">\n",
    "#               <div style=\"font-size:1.2rem;margin-bottom:6px;\">{title.split()[0]}</div>\n",
    "#               <div style=\"font-size:0.65rem;color:#64748b;margin-bottom:10px;\n",
    "#                           text-transform:uppercase;letter-spacing:.5px;\">\n",
    "#                 {\" \".join(title.split()[1:])}</div>\n",
    "#               <div style=\"font-size:2rem;font-weight:800;color:{color};\n",
    "#                           font-family:'DM Mono';\">{new_g:.1f}</div>\n",
    "#               <div style=\"font-size:0.8rem;color:#64748b;\">/ 20  ({new_p}%)</div>\n",
    "#               <div style=\"font-size:0.78rem;margin-top:6px;\n",
    "#                           color:{'#34d399' if diff > 0 else '#94a3b8'};\">\n",
    "#                 {'▲ +' if diff > 0 else ('▼ ' if diff < 0 else '')}{abs(diff):.2f} pts</div>\n",
    "#               <div style=\"margin-top:8px;display:inline-block;padding:4px 12px;\n",
    "#                           border-radius:6px;font-size:0.7rem;font-weight:800;\n",
    "#                           background:{'rgba(52,211,153,.12)' if new_g>=10 else 'rgba(251,113,133,.12)'};\n",
    "#                           color:{'#34d399' if new_g>=10 else '#fb7185'};\n",
    "#                           border:1px solid {'rgba(52,211,153,.3)' if new_g>=10 else 'rgba(251,113,133,.3)'};\">\n",
    "#                 {'PASS' if new_g>=10 else 'FAIL'}</div>\n",
    "#             </div>\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# # FOOTER\n",
    "# # ─────────────────────────────────────────────────────────────────────\n",
    "# st.markdown(\"<br><br>\", unsafe_allow_html=True)\n",
    "# st.markdown(\"\"\"\n",
    "# <div style=\"border-top:1px solid rgba(255,255,255,0.06);padding:16px 0;\n",
    "#             text-align:center;font-size:0.68rem;color:#334155;\">\n",
    "#   EduXAI · Student Performance Analytics using Explainable AI ·\n",
    "#   UCI Dataset (P. Cortez, 2008) · 1,044 Students · Normalized Prediction Model\n",
    "# </div>\n",
    "# \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
